apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: notes-app  
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: notes-app  
spec:
  type: NodePort   # or NodePort if you're on Minikube
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80

